name: build-image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 镜像标签
        required: false
        type: string
        default: latest

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "image=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"
